[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W"]

[tool.pycodestyle]
max-line-length = 100

[tool.flake8]
max-line-length = 100

[tool.mypy]
python_version = "3.10"
strict = true
